import { NextRequest, NextResponse } from 'next/server'
import { activateAutoGeneratedOption } from '@/lib/coupang/products'

export async function POST(_req: NextRequest, { params }: { params: Promise<{ vendorItemId: string }> }) {
  try {
    const { vendorItemId } = await params
    await activateAutoGeneratedOption(vendorItemId)
    return NextResponse.json({ ok: true })
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}
