import { coupangRequest } from './client'

const VENDOR_ID = process.env.COUPANG_VENDOR_ID!

interface ProductListItem {
  sellerProductId: number
  sellerProductName: string
  statusName: string
}

interface ProductDetail {
  sellerProductId: number
  sellerProductName: string
  statusName: string
  items: Array<{
    itemName: string
    marketplaceItemData?: {
      vendorItemId: number
      priceData?: { salePrice: number }
    }
    rocketGrowthItemData?: {
      vendorItemId: number
      priceData?: { salePrice: number }
    }
  }>
}

export interface CoupangProduct {
  sellerProductId: string
  sellerProductName: string
  salePrice: number
  statusName: string
  imageUrl: string
  items: Array<{
    vendorItemId: string
    itemName: string
  }>
}

export interface ProductEditData {
  name: string
  displayName: string
  brand: string
  manufacturer: string
  salePrice: number
  originalPrice: number
  saleStartedAt: string
  saleEndedAt: string
  searchTags: string[]
  maximumBuyForPerson: number
  maximumBuyForPersonPeriod: number
  unitCount: number
  outboundShippingTimeDay: number
  // identifiers
  barcode: string
  externalVendorSku: string
  modelNo: string
  // physical
  weight: number
  netWeight: number
  width: number
  length: number
  height: number
  fragile: boolean
  distributionPeriod: number
  // product-level flags
  taxType: string
  adultOnly: string
  parallelImported: string
  offerCondition: string
  images: Array<{ order: number; type: string; url: string; isCdn: boolean }>
  description: string
  items: Array<{ vendorItemId: string; itemName: string }>
}

export interface ItemInventory {
  sellerItemId: number
  amountInStock: number
  salePrice: number
  onSale: boolean
}

export async function fetchItemInventory(vendorItemId: string): Promise<ItemInventory> {
  const res = await coupangRequest<{ data: ItemInventory }>(
    'GET',
    `/v2/providers/seller_api/apis/api/v1/marketplace/vendor-items/${vendorItemId}/inventories`
  )
  return res.data
}

export async function activateAutoGeneratedOptionAll(): Promise<void> {
  await coupangRequest(
    'POST',
    '/v2/providers/seller_api/apis/api/v1/marketplace/seller/auto-generated/opt-in'
  )
}

export async function activateAutoGeneratedOption(vendorItemId: string): Promise<void> {
  await coupangRequest(
    'POST',
    `/v2/providers/seller_api/apis/api/v1/marketplace/vendor-items/${vendorItemId}/auto-generated/opt-in`
  )
}

export async function updateItemPrice(vendorItemId: string, price: number): Promise<void> {
  await coupangRequest(
    'PUT',
    `/v2/providers/seller_api/apis/api/v1/marketplace/vendor-items/${vendorItemId}/prices/${price}?forceSalePriceUpdate=true`
  )
}

export async function updateItemOriginalPrice(vendorItemId: string, originalPrice: number): Promise<void> {
  await coupangRequest(
    'PUT',
    `/v2/providers/seller_api/apis/api/v1/marketplace/vendor-items/${vendorItemId}/original-prices/${originalPrice}`
  )
}

export async function suspendProductItem(vendorItemId: string): Promise<void> {
  await coupangRequest(
    'PUT',
    `/v2/providers/seller_api/apis/api/v1/marketplace/vendor-items/${vendorItemId}/sales/stop`
  )
}

export async function resumeProductItem(vendorItemId: string): Promise<void> {
  await coupangRequest(
    'PUT',
    `/v2/providers/seller_api/apis/api/v1/marketplace/vendor-items/${vendorItemId}/sales/resume`
  )
}

export async function deleteProduct(sellerProductId: string): Promise<string> {
  const res = await coupangRequest<{ data: string }>(
    'DELETE',
    `/v2/providers/seller_api/apis/api/v1/marketplace/seller-products/${sellerProductId}`
  )
  return res.data
}

export async function requestProductApproval(sellerProductId: string): Promise<string> {
  const res = await coupangRequest<{ data: string }>(
    'PUT',
    `/v2/providers/seller_api/apis/api/v1/marketplace/seller-products/${sellerProductId}/approvals`
  )
  return res.data
}

export async function fetchProductRaw(sellerProductId: string): Promise<Record<string, unknown>> {
  const path = `/v2/providers/seller_api/apis/api/v1/marketplace/seller-products/${sellerProductId}`
  const res = await coupangRequest<{ data: Record<string, unknown> }>('GET', path)
  return res.data
}

export async function fetchProductForEdit(sellerProductId: string): Promise<ProductEditData> {
  const product = await fetchProductRaw(sellerProductId)

  const items = (product.items as Record<string, unknown>[] | undefined) ?? []
  const firstItem = items[0] as Record<string, unknown> | undefined
  let salePrice = 0, originalPrice = 0, maximumBuyForPerson = 0, unitCount = 1
  let outboundShippingTimeDay = 1, maximumBuyForPersonPeriod = 1
  let barcode = '', externalVendorSku = '', modelNo = ''
  let weight = 0, netWeight = 0, width = 0, length = 0, height = 0
  let fragile = false, distributionPeriod = 0
  if (firstItem) {
    const rgData = firstItem.rocketGrowthItemData as Record<string, unknown> | undefined
    const mpData = firstItem.marketplaceItemData as Record<string, unknown> | undefined
    const priceData = (rgData?.priceData ?? mpData?.priceData) as Record<string, unknown> | undefined
    salePrice = Number(priceData?.salePrice ?? 0)
    originalPrice = Number(priceData?.originalPrice ?? 0)
    maximumBuyForPerson = Number(firstItem.maximumBuyForPerson ?? 0)
    maximumBuyForPersonPeriod = Number(firstItem.maximumBuyForPersonPeriod ?? 1)
    unitCount = Number(firstItem.unitCount ?? 1)
    outboundShippingTimeDay = Number(firstItem.outboundShippingTimeDay ?? 1)
    if (rgData) {
      barcode = String(rgData.barcode ?? '')
      externalVendorSku = String(rgData.externalVendorSku ?? '')
      modelNo = String(rgData.modelNo ?? '')
      const sku = rgData.skuInfo as Record<string, unknown> | undefined
      if (sku) {
        weight = Number(sku.weight ?? 0)
        netWeight = Number(sku.netWeight ?? 0)
        width = Number(sku.width ?? 0)
        length = Number(sku.length ?? 0)
        height = Number(sku.height ?? 0)
        fragile = Boolean(sku.fragile ?? false)
        distributionPeriod = Number(sku.distributionPeriod ?? 0)
      }
    }
  }

  const rawImages = (product.images as Record<string, unknown>[] | undefined) ?? []
  const images = rawImages.map(img => ({
    order: Number(img.imageOrder ?? 0),
    type: String(img.imageType ?? 'DETAIL'),
    url: String(img.cdnPath ?? img.vendorPath ?? ''),
    isCdn: !!img.cdnPath,
  }))

  const contents = (product.contents as Record<string, unknown>[] | undefined) ?? []
  let description = ''
  outer: for (const c of contents) {
    for (const d of (c.contentDetails as Record<string, unknown>[] | undefined) ?? []) {
      if (d.detailType === 'TEXT') { description = String(d.content ?? ''); break outer }
    }
  }

  const rawTags = (product.searchTags as unknown[]) ?? []
  const searchTags = rawTags.map(t => String(t)).filter(Boolean)

  return {
    name: String(product.sellerProductName ?? ''),
    displayName: String(product.displayProductName ?? ''),
    brand: String(product.brand ?? ''),
    manufacturer: String(product.manufacture ?? ''),
    salePrice,
    originalPrice,
    saleStartedAt: String(product.saleStartedAt ?? ''),
    saleEndedAt: String(product.saleEndedAt ?? ''),
    searchTags,
    maximumBuyForPerson,
    maximumBuyForPersonPeriod,
    unitCount,
    outboundShippingTimeDay,
    barcode,
    externalVendorSku,
    modelNo,
    weight,
    netWeight,
    width,
    length,
    height,
    fragile,
    distributionPeriod,
    taxType: String(product.taxType ?? 'TAX'),
    adultOnly: String(product.adultOnly ?? 'EVERYONE'),
    parallelImported: String(product.parallelImported ?? 'NOT_PARALLEL_IMPORTED'),
    offerCondition: String(product.offerCondition ?? 'NEW'),
    images,
    description,
    items: items.map(item => {
      const rgData = item.rocketGrowthItemData as Record<string, unknown> | undefined
      const mpData = item.marketplaceItemData as Record<string, unknown> | undefined
      const vendorItemId = String(rgData?.vendorItemId ?? mpData?.vendorItemId ?? '')
      return { vendorItemId, itemName: String(item.itemName ?? '') }
    }),
  }
}

export async function updateProduct(sellerProductId: string, updates: Partial<ProductEditData> & { price?: number }): Promise<void> {
  const product = await fetchProductRaw(sellerProductId)

  if (updates.name !== undefined) product.sellerProductName = updates.name
  if (updates.displayName !== undefined) product.displayProductName = updates.displayName
  if (updates.brand !== undefined) product.brand = updates.brand
  if (updates.manufacturer !== undefined) product.manufacture = updates.manufacturer
  if (updates.saleStartedAt !== undefined) product.saleStartedAt = updates.saleStartedAt
  if (updates.saleEndedAt !== undefined) product.saleEndedAt = updates.saleEndedAt
  if (updates.searchTags !== undefined) product.searchTags = updates.searchTags
  if (updates.taxType !== undefined) product.taxType = updates.taxType
  if (updates.adultOnly !== undefined) product.adultOnly = updates.adultOnly
  if (updates.parallelImported !== undefined) product.parallelImported = updates.parallelImported

  const itemFields = ['price', 'originalPrice', 'salePrice', 'maximumBuyForPerson', 'maximumBuyForPersonPeriod',
    'unitCount', 'outboundShippingTimeDay', 'barcode', 'externalVendorSku', 'modelNo',
    'weight', 'netWeight', 'width', 'length', 'height', 'fragile', 'distributionPeriod']
  if (itemFields.some(f => (updates as Record<string, unknown>)[f] !== undefined)) {
    const items = (product.items as Record<string, unknown>[] | undefined) ?? []
    for (const item of items) {
      const it = item as Record<string, unknown>
      if (updates.maximumBuyForPerson !== undefined) it.maximumBuyForPerson = updates.maximumBuyForPerson
      if (updates.maximumBuyForPersonPeriod !== undefined) it.maximumBuyForPersonPeriod = updates.maximumBuyForPersonPeriod
      if (updates.unitCount !== undefined) it.unitCount = updates.unitCount
      if (updates.outboundShippingTimeDay !== undefined) it.outboundShippingTimeDay = updates.outboundShippingTimeDay
      for (const key of ['rocketGrowthItemData', 'marketplaceItemData'] as const) {
        const data = it[key] as Record<string, unknown> | undefined
        if (!data) continue
        if (data.priceData) {
          const pd = data.priceData as Record<string, unknown>
          if (updates.price !== undefined) pd.salePrice = updates.price
          if (updates.salePrice !== undefined) pd.salePrice = updates.salePrice
          if (updates.originalPrice !== undefined) pd.originalPrice = updates.originalPrice
        }
        if (key === 'rocketGrowthItemData') {
          if (updates.barcode !== undefined) data.barcode = updates.barcode
          if (updates.externalVendorSku !== undefined) data.externalVendorSku = updates.externalVendorSku
          if (updates.modelNo !== undefined) data.modelNo = updates.modelNo
          const skuFields = ['weight', 'netWeight', 'width', 'length', 'height', 'fragile', 'distributionPeriod'] as const
          if (skuFields.some(f => (updates as Record<string, unknown>)[f] !== undefined)) {
            const sku = (data.skuInfo ?? {}) as Record<string, unknown>
            if (updates.weight !== undefined) sku.weight = updates.weight
            if (updates.netWeight !== undefined) sku.netWeight = updates.netWeight
            if (updates.width !== undefined) sku.width = updates.width
            if (updates.length !== undefined) sku.length = updates.length
            if (updates.height !== undefined) sku.height = updates.height
            if (updates.fragile !== undefined) sku.fragile = updates.fragile
            if (updates.distributionPeriod !== undefined) sku.distributionPeriod = updates.distributionPeriod
            data.skuInfo = sku
          }
        }
      }
    }
  }

  if (updates.images !== undefined) {
    product.images = updates.images.map(img => ({
      imageOrder: img.order,
      imageType: img.type,
      ...(img.isCdn ? { cdnPath: img.url } : { vendorPath: img.url }),
    }))
  }

  if (updates.description !== undefined) {
    const contents = (product.contents as Record<string, unknown>[] | undefined) ?? []
    let found = false
    outer: for (const c of contents) {
      for (const d of (c.contentDetails as Record<string, unknown>[] | undefined) ?? []) {
        if (d.detailType === 'TEXT') { d.content = updates.description; found = true; break outer }
      }
    }
    if (!found) {
      contents.push({ contentsType: 'TEXT', contentDetails: [{ content: updates.description, detailType: 'TEXT' }] })
      product.contents = contents
    }
  }

  await coupangRequest('PUT', '/v2/providers/seller_api/apis/api/v1/marketplace/seller-products', product)
}

export interface CreateProductData {
  sellerProductName: string
  displayCategoryCode: number
  vendorId: string
  vendorUserId: string
  saleStartedAt: string
  saleEndedAt: string
  displayProductName: string
  brand: string
  generalProductName: string
  manufacture: string
  searchTags: string[]
  requested: boolean
  rfmInboundName: string
  // item
  itemName: string
  salePrice: number
  originalPrice: number
  maximumBuyForPerson: number
  maximumBuyForPersonPeriod: number
  outboundShippingTimeDay: number
  unitCount: number
  adultOnly: string
  taxType: string
  parallelImported: string
  overseasPurchased: string
  pccNeeded: boolean
  offerCondition: string
  barcode: string
  emptyBarcode: boolean
  emptyBarcodeReason: string
  externalVendorSku: string
  modelNo: string
  weight: number
  netWeight: number
  width: number
  length: number
  height: number
  fragile: boolean
  distributionPeriod: number
  images: Array<{ order: number; type: string; url: string; isCdn: boolean }>
  description: string
  certifications: Array<{ certificationType: string; certificationCode: string }>
  notices: Array<{ noticeCategoryName: string; noticeCategoryDetailName: string; content: string }>
  attributes: Array<{ attributeTypeName: string; attributeValueName: string; exposed: string }>
}

export async function createProduct(data: CreateProductData): Promise<number> {
  const images = data.images.map(img => ({
    imageOrder: img.order,
    imageType: img.type,
    ...(img.isCdn ? { cdnPath: img.url } : { vendorPath: img.url }),
  }))

  const contents = data.description
    ? [{ contentsType: 'TEXT', contentDetails: [{ content: data.description, detailType: 'TEXT' }] }]
    : []

  const skuInfo = {
    fragile: data.fragile,
    weight: data.weight || undefined,
    netWeight: data.netWeight || undefined,
    width: data.width || undefined,
    length: data.length || undefined,
    height: data.height || undefined,
    quantityPerBox: 1,
    distributionPeriod: data.distributionPeriod,
    expiredAtManaged: data.distributionPeriod > 0,
  }

  const barcodeFields = data.emptyBarcode
    ? { emptyBarcode: true, emptyBarcodeReason: data.emptyBarcodeReason || 'AUTO_GENERATED' }
    : { barcode: data.barcode || undefined }

  const body = {
    sellerProductName: data.sellerProductName,
    displayCategoryCode: data.displayCategoryCode,
    vendorId: data.vendorId,
    saleStartedAt: data.saleStartedAt,
    saleEndedAt: data.saleEndedAt,
    displayProductName: data.displayProductName || undefined,
    brand: data.brand || undefined,
    generalProductName: data.generalProductName || undefined,
    manufacture: data.manufacture || undefined,
    marketplaceShippingAndReturnInfo: null,
    vendorUserId: data.vendorUserId,
    requested: data.requested,
    searchTags: data.searchTags.length > 0 ? data.searchTags : undefined,
    items: [{
      itemName: data.itemName,
      maximumBuyForPerson: data.maximumBuyForPerson,
      maximumBuyForPersonPeriod: data.maximumBuyForPersonPeriod,
      outboundShippingTimeDay: data.outboundShippingTimeDay,
      unitCount: data.unitCount,
      adultOnly: data.adultOnly,
      taxType: data.taxType,
      parallelImported: data.parallelImported,
      overseasPurchased: data.overseasPurchased,
      pccNeeded: data.pccNeeded,
      offerCondition: data.offerCondition,
      images,
      notices: data.notices.length > 0 ? data.notices : undefined,
      attributes: data.attributes.length > 0 ? data.attributes : undefined,
      contents,
      certifications: data.certifications.length > 0
        ? data.certifications.map(c => ({ certificationType: c.certificationType, certificationCode: c.certificationCode, certificationAttachments: null }))
        : [{ certificationType: 'NOT_REQUIRED', certificationCode: '', certificationAttachments: null }],
      rocketGrowthItemData: {
        ...barcodeFields,
        externalVendorSku: data.externalVendorSku || undefined,
        modelNo: data.modelNo || undefined,
        skuInfo,
        priceData: {
          originalPrice: data.originalPrice,
          salePrice: data.salePrice,
        },
      },
      marketplaceItemData: null,
    }],
    registrationType: 'RFM',
    rocketGrowthAdditionalInformation: {
      rfmInboundName: data.rfmInboundName || data.sellerProductName,
      legalAgreement: 'AGREE',
    },
  }

  const res = await coupangRequest<{ data: { data: number } }>('POST', '/v2/providers/seller_api/apis/api/v1/marketplace/seller-products', body)
  return res.data.data
}

export interface ProductStatusHistoryEntry {
  status: string
  comment: string
  createdBy: string
  createdAt: string
}

export async function fetchProductStatusHistory(sellerProductId: string): Promise<ProductStatusHistoryEntry[]> {
  const res = await coupangRequest<{ data: ProductStatusHistoryEntry[] }>(
    'GET',
    `/v2/providers/seller_api/apis/api/v1/marketplace/seller-products/${sellerProductId}/histories`
  )
  return res.data ?? []
}

export interface InflowStatus {
  vendorId: string
  restricted: boolean
  registeredCount: number
  permittedCount: number | null
}

export async function fetchInflowStatus(): Promise<InflowStatus> {
  const res = await coupangRequest<{ data: InflowStatus }>(
    'GET',
    '/v2/providers/seller_api/apis/api/v1/marketplace/seller-products/inflow-status'
  )
  return res.data
}

export interface ProductSummary {
  sellerProductId: number
  sellerProductName: string
  displayCategoryCode: number | null
  vendorId: string
  saleStartedAt: string
  saleEndedAt: string
  brand: string | null
  statusName: string
  createdAt: string
}

export async function fetchProductByExternalSku(sku: string): Promise<ProductSummary[]> {
  const res = await coupangRequest<{ data: ProductSummary[] }>(
    'GET',
    `/v2/providers/seller_api/apis/api/v1/marketplace/seller-products/external-vendor-sku-codes/${encodeURIComponent(sku)}`
  )
  return res.data ?? []
}

export async function fetchProducts(): Promise<CoupangProduct[]> {
  const listPath = `/v2/providers/seller_api/apis/api/v1/marketplace/seller-products?vendorId=${VENDOR_ID}&status=APPROVED&limit=100`
  const listRes = await coupangRequest<{ data: ProductListItem[] }>('GET', listPath)
  const list = listRes.data ?? []

  const results: CoupangProduct[] = []
  for (const p of list) {
    try {
      const detailPath = `/v2/providers/seller_api/apis/api/v1/marketplace/seller-products/${p.sellerProductId}`
      const detailRes = await coupangRequest<{ data: ProductDetail }>('GET', detailPath)
      const d = detailRes.data
      const firstItem = d.items?.[0]
      const salePrice =
        firstItem?.marketplaceItemData?.priceData?.salePrice ??
        firstItem?.rocketGrowthItemData?.priceData?.salePrice ?? 0

      const firstImage = (d as unknown as Record<string, unknown>).images as Record<string, unknown>[] | undefined
      const imageUrl = String(firstImage?.[0]?.cdnPath ?? firstImage?.[0]?.vendorPath ?? '')

      results.push({
        sellerProductId: String(d.sellerProductId),
        sellerProductName: d.sellerProductName,
        salePrice,
        statusName: d.statusName,
        imageUrl,
        items: (d.items ?? []).map(item => ({
          // prefer RG vendorItemId for matching with RG inventory API
          vendorItemId: String(
            item.rocketGrowthItemData?.vendorItemId ??
            item.marketplaceItemData?.vendorItemId ?? ''
          ),
          itemName: item.itemName ?? '',
        })),
      })
    } catch {
      // skip individual product if detail fetch fails
    }
  }
  return results
}
