import { NextResponse } from 'next/server'
import { activateAutoGeneratedOptionAll } from '@/lib/coupang/products'

export async function POST() {
  try {
    await activateAutoGeneratedOptionAll()
    return NextResponse.json({ ok: true })
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}
